- type: gameMap
  id: de_train
  mapName: 'de_train'
  mapPath: /Maps/CS/train.yml
  minPlayers: 0
  stations:
   deTrain:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: "deTrain"
        - type: StationJobs
          availableJobs:
            Lawyer: [ -1, -1 ]
            Janitor: [-1, -1 ]

