- type: entity
  id: CsTrainSpeedingKillZone
  name: Speeding Train
  components:
  - type: Sprite
    sprite: Objects/counterstrike/Structures/Obstructions/Cars/train.rsi
    state: train0
    drawdepth: Doors
  - type: TimedDespawn
    lifetime: 7
  - type: Physics
    bodyType: Dynamic
    bodyStatus: InAir
    angularDamping: 0
    linearDamping: 0
  - type: Fixtures
    fixtures:
      train:
        shape:
          !type:PhysShapeAabb
          bounds: "-4,-1.5,4,1.25"
        density: 500
        hard: false
        layer:
        - MobLayer
        mask:
        - MobMask
  - type: CsTrainKillZone
    speed: 4
    damage:
      types:
        Piercing: 200

- type: entity
  id: CsTrainSpeedingSpawner
  name: Speeding Train Spawner
  components:
  - type: Sprite
    sprite: Markers/markers.rsi
    state: spawn
    visible: false
  - type: Timer
  - type: TimedSpawner
    prototypes:
    - CsTrainSpeedingKillZone
    intervalSeconds: 180
    minimumEntitiesSpawned: 1
    maximumEntitiesSpawned: 1
