- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hire
  accessGroups:
  - AllAccess
  access:
  - CentralCommand



- type: startingGear
  id: BoxerGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatPoliceCap
    jumpsuit: ClothingUniformPoliceOutfit
    belt: ClothingBeltSecurityWebbing

- type: chameleonOutfit
  id: BoxerChameleonOutfit
  job: Boxer
  equipment:
    head: ClothingHeadHatBlacksoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorGray
    jumpsuit: UniformShortsRedWithTop
    neck: ClothingNeckScarfStripedRed
