- type: job
  id: SalvageSpecialist
  name: Police BABAGRAD.
  description: that is sound of the police.
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 0 # 2.5 hrs
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatPoliceCap
    jumpsuit: ClothingUniformPoliceOutfit
    belt: ClothingBeltSecurityWebbing
    pocket1: WeaponCaseGlock
    # pocket2: WeaponTTTTaser -- СКОРО
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: SalvageSpecialistChameleonOutfit
  job: SalvageSpecialist
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGasExplorer
    outerClothing: ClothingOuterWinterMiner
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesColorBlack

