# CS Base Weapon Prototypes

- type: entity
  name: BasePistolCS
  parent: [BaseWeaponPistol, BaseSecurityContraband]
  id: BasePistolCS
  description: CS pistol base.
  abstract: true
  components:
  - type: Gun
    fireRate: 5
    minAngle: 3
    maxAngle: 60
    angleIncrease: 5
    angleDecay: 15
    selectedMode: SemiAuto
    availableModes: [ SemiAuto ]
    soundGunshot: { path: /Audio/Weapons/counterstrike/guns/m4s.ogg }
  - type: Item
    storedOffset: 0,-2

- type: entity
  name: BaseRiffleCS
  parent: [BaseWeaponRifle, BaseSecurityContraband]
  id: BaseRiffleCS
  description: CS rifle base.
  abstract: true
  components:
  - type: Gun
    fireRate: 7
    minAngle: 5
    maxAngle: 60
    angleIncrease: 7
    angleDecay: 15
    selectedMode: FullAuto
    availableModes: [ FullAuto ]
    soundGunshot: { path: /Audio/Weapons/counterstrike/guns/ak.ogg }
  - type: GunWieldBonus
    minAngle: -1
    maxAngle: -1
